config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :profiles
  end

  resources :profiles

  resources :groups, param: :code do
    resources :members
  end

  get "/crossroads", to: "groups#crossroads", as: "crossroads"

  resources :members

  root "groups#landing"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = User.find(params[:user_id])
    @profile.save
    redirect_to root_path
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to @profile
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :fullname, :age, :user_id)
  end
end

app/views/profiles/new.html.erb
<div class="jumbotron w-50 mx-auto p-4 shadow jumboform">
  <h2 class="title">Profile</h2>
  <p class="lead">Let us know more about you!</p>
  <hr>
  <div class="form-group">
    <%=form_with model: @profile, url: user_profiles_path, local: true do |f|%>
      <%=f.label 'Name'%>
      <%=f.text_field :username, class:"form-control", required: true%>
      <%#=f.label 'Full Name'%>
      <%#=f.text_field :fullname, class:"form-control"%>
      <%=f.label :age%>
      <%=f.number_field :age, class:"form-control"%>
      <button type="submit" class="btn btn-sm btn-danger font-weight-bold mt-3">Submit</button>
    <%end%>
  </div>

app/views/profiles/show.html.erb
<div class="jumbotron w-50 mx-auto p-4 shadow jumboform">
  <h2 class="title">Profile</h2>
  <h3>Welcome <%=@profile.username%></h3>
  <h5>You can view and edit your profile details here.</h5>
  <div class="form-group">
    <%= form_with model: @profile, local: true do |f| %>
      <div class="field">
        <%= f.label "Name" %>
        <%= f.text_field :username, class: "form-control", required: true %>
      </div>
      <div class="field">
        <%= f.label :age %>
        <%= f.text_field :age, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.submit "Save Changes", class:"btn btn-primary mt-3 font-weight-bold" %>
      </div>
    <% end %>
  </div>
</div>