config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :profiles
  end

  resources :profiles

  resources :groups, param: :code do
    resources :members
  end

  get "/crossroads", to: "groups#crossroads", as: "crossroads"

  resources :members

  root "groups#landing"
end

app/models/group.rb
class Group < ApplicationRecord
  validates :code, uniqueness: true
  has_many :members, dependent: :destroy

  def to_param
    code
  end

  def is_not_full?
    self.members.size != self.size
  end

  def owner
    self.members.first.user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :crossroads, :landing]

  def index
    @user = User.find(current_user.id)
    @groups = @user.groups
    redirect_to new_group_path if @groups.size == 0
  end

  def show
    @map = "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE"]}&libraries=places&callback=initMap"
    @group = Group.find_by(code: params[:code])
    @members = @group.members.all
    if user_signed_in?
      @member = Member.find_by user_id: current_user.id
    elsif cookies[:current_member]
      @member = Member.find(cookies[:current_member])
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save
    @user = User.find(current_user.id)
    @member = Member.new(name: current_user.profile.username)
    @member.group = @group
    @member.user = @user
    @member.place = "Singapore"
    @member.icon = Random.new.rand(25)
    @member.save
    redirect_to @group
  end

  def destroy
    @group = Group.find_by(code: params[:code])
    @group.destroy
    redirect_to groups_path
  end

  def landing
  end

  def crossroads
    @group = Group.find_by(code: params[:code])
    return redirect_to root_path(:error => true) if @group == nil
    if user_signed_in?
      if @group.owner == User.find(current_user.id)
        return redirect_to @group
      elsif User.find(current_user.id).groups.include? @group
        return redirect_to @group
      elsif @group.is_not_full?
        @user = User.find(current_user.id)
        @member = Member.new(name: current_user.profile.username)
        @member.group = @group
        @member.user = @user
        @member.save
        redirect_to @group
      end
    elsif cookies[:current_member]
      member_id = cookies[:current_member]
      if Member.find(member_id).group == @group
        return redirect_to @group
      end
    end
    @member = Member.new
  end

  private

  def group_params
    params.require(:group).permit(:code, :size)
  end
end

app/views/groups/crossroads.html.erb
<div class="jumbotron w-50 mx-auto p-4 shadow jumboform">
  <%if @group.is_not_full?%>
    <h1>Welcome to <%=@group.code%></h1>
    <hr>
    <p>
      Please enter your name.
    </p>
    <%=form_with model: @member, url: group_members_path(@group), local: true do |f| %>
      <div class="form-group d-md-flex justify-content-between">
        <%=f.text_field :name, class: "form-control m-1", placeholder: "Name"%>
        <button type="submit" class="btn btn-sm btn-danger font-weight-bold m-1">GO</button>
      </div>
    <%end%>
  <%else%>
    <h1 class="display-4 title">Sorry!</h1>
    <%=link_to "Group is full! Click here to continue.", root_path%>
  <%end%>
</div>

app/views/groups/index.html.erb
<div class="container-fluid sidebars">
  <div class="row m-5 mb-3">
    <%@groups.each do |group|%>
      <%if group.owner == @user%>
        <div class="col-3 mb-3">
          <div class="card shadow">
            <div class="card-header font-weight-bold">
              <%=link_to group.code, group_path(group.code) %>
            </div>
            <ul class="list-group list-group-flush">
              <%group.members.each do |member|%>
                <li class="list-group-item"><%=member.name%></li>
              <%end%>
            </ul>
            <div class="card-footer">
              <%=
							link_to 'Delete', group_path(group),
							method: :delete,
							data: { confirm: 'Are you sure?' },
							class: "text-danger"
							%></div>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/groups/landing.html.erb
<div class="jumbotron w-50 mx-auto p-4 shadow jumboform">
  <% if user_signed_in? %>
    <h1 class="display-4 title">Hey <%=current_user.profile.username%></h1>
  <%else%>
    <h1 class="display-4 title">RUMU</h1>
    <p class="lead">Ready Up; Meet Up. <br>
      Find the perfect place to meet: <span class="title">all the time, any time.</span>
    </p>
  <%end%>
  <hr>
  <%if params[:error]%>
    <p class="text-danger">Group not found!</p>
  <%end%>
  <p>
    Enter group code to start.
  </p>
  <%=form_with url: crossroads_path, method: :get, local: true, html: { autocomplete: "off" } do |f| %>
    <div class="form-group d-md-flex justify-content-between">
      <%=f.text_field :code, class: "form-control m-1", placeholder: "Group Code"%>
      <button type="submit" class="btn btn-sm btn-danger font-weight-bold m-1">GO</button>
    </div>
  <%end%>
  <hr>
  <% if user_signed_in? %>
    <%=link_to "No group code? Create your own here.", new_group_path%>
  <%else%>
    <%=link_to "No group code? Sign up and create your own here.", new_user_registration_path%>
  <%end%>
</div>

app/views/groups/new.html.erb
<div class="jumbotron w-50 mx-auto p-4 shadow jumboform">
  <h2 class="title">Create group</h2>
  <p class="lead">Enter a code for sharing and set the maximum group size</p>
  <hr>
  <div class="form-group">
    <%=form_with model: @group, local: true, html: { autocomplete: "off" } do |f|%>
      <%=f.label :code%>
      <%=f.text_field :code, class: "form-control", required: true%>
      <%=f.label :size%>
      <%=f.text_field :size, class: "form-control", required: true%>
      <button type="submit" class="btn btn-sm btn-danger font-weight-bold mt-3">Submit</button>
    <%end%>
  </div>
</div>

app/views/groups/show.html.erb
<div id='test'></div>
<div class="container-fluid h-100">
  <div class="row h-100 pt-3">
    <div class="col-lg-3 scrolly sidebars">
      <div class="card shadow">
        <div class="card-header title text-uppercase"><%=@group.code%> | Members</div>
        <ul class="list-group-flush p-0">
          <%@members.each_with_index do |member, index|%>
            <%if member == @member%>
              <li class="list-group-item">
                <div class="d-flex align-items-center justify-content-between">
                  <div class="font-weight-bold"><%=member.name%></div>
                  <span class="iconNum d-none displayme"><%=member.icon%></span>
                  <div class="iconSelector selectme">
                    <%=image_tag image_url('aquaman.png'), {:class => 'memIcon d-none deleteme'}%>
                  </div>
                </div>
                <small>
                  <div><%=member.place%></div>
                </small>
                <div class="input-group input-group-sm mt-1">
                  <input class="form-control" id="person" placeholder="Search / Get Location"/>
                  <div class="input-group-append">
                    <button class="btn btn-sm btn-info" id="currentLocation"><i class="fa fa-map-pin"></i></button>
                    <span class="btn btn-success greenButton d-none" id="place">Mark</span>
                    <label for="confirm" class="btn btn-success m-0 disabled greenButton" id="magicbutton" disabled>Update</label>
                  </div>
                </div>
              </li>
            <%else%>
              <li class="list-group-item">
                <div class="d-flex align-items-center justify-content-between">
                  <div class="font-weight-bold"><%=member.name%></div>
                  <span class="iconNum d-none"><%=member.icon%></span>
                  <div class="iconSelector">
                    <%=image_tag image_url('aquaman.png'), {:class => 'memIcon d-none'}%>
                  </div>
                </div>
                <small>
                  <div><%=member.place%></div>
                </small>
              </li>
            <%end%>
          <%end%>
        </ul>
      </div>
    </div>
    <div class="col-lg-6">
      <!-- <div id="map" class="row w-100 shadow mx-auto"></div> -->
      <div class="row">
        <div class="input-group shadow" id="midFinder">
          <select class="custom-select" id="type" aria-label="Example select with button addon">
            <option value="cafe">Coffee</option>
            <option value="restaurant">Restaurants</option>
            <option value="bar">Bars</option>
            <option value="shopping_mall">Shopping</option>
          </select>
          <div class="input-group-append">
            <button class="btn btn-danger" type="button" id ="calc"><i class="fa fa-crosshairs"></i></button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 scrolly sidebars">
      <div class="card shadow">
        <div class="card-header title text-uppercase">Results</div>
        <ul class="list-group-flush p-0 d-none" id="listBoard">
        </ul>
      </div>
    </div>
  </div>
</div>
<%= form_for :member, url: member_path(@member), method: :patch do |form| %>
  <%= form.hidden_field :lat, {:id => "lat"} %>
  <%= form.hidden_field :lon, {:id => "lon"} %>
  <%= form.hidden_field :place, {:id => "address"} %>
  <%= form.hidden_field :icon, {:id => "icon"} %>
  <%= form.submit(class: "d-none", value: "Submit", id: "confirm", disabled: true) %>
<% end %>
<div class="d-none">
  <div id="allName">
    <%@members.each do |member|%>
      <div class="allNames"><%= member.name %></div>
    <%end%>
  </div>
  <div id="allLat">
    <%@members.each do |member|%>
      <div class="lats"><%= member.lat %></div>
    <%end%>
  </div>
  <div id="allLon">
    <%@members.each do |member|%>
      <div class="lons"><%= member.lon %></div>
    <%end%>
  </div>
  <div id="allSel">
    <%@members.each do |member|%>
      <div class="allSels"><%= member.icon %></div>
    <%end%>
  </div>
</div>
<script src='<%=@map%>'
	    async defer></script>