config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :profiles
  end

  resources :profiles

  resources :groups, param: :code do
    resources :members
  end

  get "/crossroads", to: "groups#crossroads", as: "crossroads"

  resources :members

  root "groups#landing"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>#RUMU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Righteous" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-lg">
      <%=link_to 'RUMU', root_path, class: "navbar-brand title"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%cookies.delete :current_member%>
            <%if current_user.profile%>
              <%=link_to current_user.profile.username, profile_path(current_user.profile.id), class: "nav-item nav-link"%>
            <%else%>
              <%=link_to 'Create Profile', new_user_profile_path(current_user.id), class: "nav-item nav-link"%>
            <%end%>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Groups
              </a>
              <div class="dropdown-menu">
                <%=link_to 'List My Groups', groups_path, class: "dropdown-item"%>
                <%=link_to 'New Group', new_group_path, class: "dropdown-item"%>
              </div>
            </div>
          </div>
          <div class="navbar-nav">
            <span class="nav-item navbar-text text-white"><%= notice %></span>
            <span class="nav-item navbar-text text-danger"><%= alert %></span>
            <%= link_to'Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
          <% else %>
            <%= link_to'Login', new_user_session_path, class: "nav-item nav-link"  %>
            <%= link_to'Sign Up', new_user_registration_path, class: "nav-item nav-link"  %>
            <span class="nav-item navbar-text text-white"><%= notice %></span>
            <span class="nav-item navbar-text text-danger"><%= alert %></span>
          </div>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>